### ISSUE TITLE
Propuestas tecnológicas para Omegalul

### ISSUE THREAD

**Issue by kevinrobayna** [AiramNavas/omegalul#1]
| Framework | Why?|
| ----------- | ----------- |
|  Ruby on Rails | Facil de usar y desplegar con heroku y es bastante rapido de hacer un producto       |
|  MDX + Next.js | Muy fácil de trabajar y con MDX cualquiera puede escribir los eventos (no es necesario conocimiento dev, aparte nos libramos de tener royos WYISWYG  |
| Js/Ts + Node (Firebase) | https://github.com/AiramNavas/omegalul/issues/1#issuecomment-1191562192 | 
| Svelte + Golang | https://github.com/AiramNavas/omegalul/issues/1#issuecomment-1191987451 |
| Svelte + Nest.js | https://github.com/AiramNavas/omegalul/issues/1#issuecomment-1191987451 |
| Vue + Nest.js | Winner! |

**Comment by kevinrobayna** [comment]
Yo creo que deberíamos usar un framework que facilite todo lo máximo posible (o sea algo de usar para nosotros)

**Ruby on Rails** en mi opinion es bastante fácil de usar y tiene suficientes configuraciones hechas por defecto.

Referencias:
https://guides.rubyonrails.org/getting_started.html
https://elements.heroku.com/addons/heroku-postgresql

Otra opción que yo creo que deberíamos tener en cuenta es **MDX** (Markdown + React) y **Next.js** (express js en esteroides) Esto facilita bastante escribir articulos, eventos, emails etc. (sin conocimiento de html (casi)

Referencias:
https://blog.jetbrains.com/webstorm/2021/10/building-a-blog-with-next-js-and-mdx/
https://www.joshwcomeau.com/react/wonderful-emails-with-mjml-and-mdx/

**Comment by canary255** [comment]
No se muy bien del todo que es lo que vamos a hacer respecto a la página, leí que era sobre todo para tema informativo, noticias, que tenga un registro, etc.

Yo las herramientas que mejor conozco son:

- Node.js
- React con los hooks
- Express.js
- y de ORM sé Sequelize (Aunque Mongoose tiene la misma estructura que este)

Luego así suelto +/- me sé Java y Python, pero no de Spring ni Django :(

Si al final usan una tecnología diferente (como lo de Ruby On Rails), le meteré caña y así aprendo también!

Por otra parte, para el tema de login, registro, base de datos, etc... está **Firebase**, que es de Google (Solo por decir que es de google van a decir que no jajajaja, pero lo pongo igual)
Con ello se puede hacer la parte del registro, login, tiene también un gestor de archivos en nube y una base de datos NoSQL
[https://firebase.google.com/products-build](https://firebase.google.com/products-build)

Desventaja: Si no pagas (obviamente), pues tienes uso limitado

Creo que heroku ofrece las mismas características que firebase e incluso puede salir mejor.

A ver que comentan los demás sobre las tecnologías que usan y de ahí hablarlo y tener mejor las ideas :)

**Comment by AndresCalimero** [comment]
Yo votaría por una arquitectura [Jamstack](https://jamstack.org/), separando completamente la presentación de la lógica de negocio, a efectos practicos consistiría en desarrollar el frontend de tal forma que se pueda desplegar solamente publicando los artefactos generados tras el build (HTML, CSS, JS y otros assets estaticos), de esta forma todo el HTML de la aplicación se reenderizaría en el navegador del cliente y el frontend solo podría interactuar con el backend mediante llamadas a su API pública.

Algunas ventajas que le veo a esa arquitectura:

- Nos podriamos dividir entre frontend y backend de forma más sencilla, ya que realmente serían dos proyectos distintos.
- Nos obligaría a tener que definir una buena API pública con todas las funcionalidades que necesite el frontend, tener una API pública de calidad nos permitiría implementar otro tipo de interfaces e integraciones más facilmente.
- El despliegue del frontend sería trivial, se podría usar un CDN.
- No estariamos atados a ninguna tecnología, se podría cambiar el frontend completamente sin necesidad de tocar el backend y viceversa.
- No necesitariamos de un servidor para reenderizar el HTML en cada petición, por lo que nos ahorramos el coste computacional.

Como desventajas:

- No tendriamos un framework completo con mucha funcionalidad ya implementada (como Ruby on Rails), aunque también podría ser una ventaja, ese tipo de framework son complejos y tienen una curva de aprendizaje bastante elevada, ademas de las limitaciones que imponen por su propia naturaleza.
- A diferencia de una arquitectura SSR más tradicional, como la que usa Ruby on Rails o PHP, donde solo sería necesario desplegar un servidor, con esta arquitectura tendriamos que desplegar el frontend y el backend de forma independiente, aunque no supone un incremento significativo en la complejidad del despliegue podría hacer que aumente ligeramente el coste de la infraestructura.

También propongo seguir una aproximación API-first y diseñar la API usando [OpenAPI 3](https://www.openapis.org/) antes de empezar con la implementación, para facilitar el diseño de la API podríamos usar herramientas como [Swagger Editor](https://editor.swagger.io). Tener una definición de la API en el formato de OpenAPI nos permitiría usar el ecosistema de herramientas que hay alrededor de OpenAPI, algunas de las más interesantes serían los [generadores de código para clientes y servidores](https://openapi-generator.tech/).

# Frontend

| Tecnología | Why?|
| ----------- | ----------- |
|  Svelte + router SPA sencillo, usando TypeScript | [Svelte](https://svelte.dev/) es una librería de JS para frontend que está [ganando mucha popularidad](https://2021.stateofjs.com/en-US/libraries/front-end-frameworks/), difiere del resto de librerías de frontend porque no usa un DOM virtual, por lo que he visto es bastante simple de usar, más sencillo que React, Angular o incluso que Vue |

# Backend e infraestructura:

Aquí voy a hacer tres propuestas:

- **Propuesta A**: claramente overkill, va a requerir más esfuerzo pero usa más tecnologias interesantes y se podría aprender mucho.
- **Propuesta B**: más razonable que la anterior si se quiere optimizar el tiempo de desarrollo, requerirá menos esfuerzo pero se aprenderá menos también.
- **Propuesta C**: si lo que nos interesa es hacerlo rapido y con el menor esfuerzo posible entonces creo que esta sería una de las mejores opciones.

Yo personalmente me decanto por la propuesta A porque me gustaría aprovechar el proyecto para aprender lo máximo posible, pero entiendo que no todo el mundo esté por la labor o le parezcan interesantes las tecnologías que he mencionado.

## Propuesta A

Microservicios usando [Dapr](https://dapr.io/) desplegados en un cluster de Kubernetes, lo más sencillo sería usar NodeJS con TypeScript para unificar el lenguaje de programación entre el frontend y el backend, pero se podría valorar usar otros lenguajes. Go podría ser una opción interesante para reducir el consumo de recursos, reduciendo así el coste de la infraestructura.

### Infraestructura

- Cluster de Kubernetes usando [K3s](https://k3s.io/), podría ser un cluster de un solo nodo si queremos optimizar costes, el tema económico habrá que discutirlo también.
- Para la autenticación y autorización se podría usar el ecosistema de [Ory](https://www.ory.sh/).
- Todo se desplegaría mediante [Helm Charts](https://helm.sh/) siguiendo una estrategia [GitOps](https://about.gitlab.com/topics/gitops/), se podría usar [Flux CD](https://fluxcd.io/).

## Propuesta B

Servidor API usando [NestJS](https://nestjs.com/) y TypeScript. NestJS es un framework de NodeJS para aplicaciones del lado del servidor, ya implementa bastante funcionalidad y está muy bien diseñado (en mi opinión).

### Infraestructura

- Servidor dedicado, VPS o servicio gestionado que soporte contenedores de Docker.
- Para la autenticación y autorización se podría usar algún servicio gestionado como [Auth0](https://auth0.com/es).

## Propuesta C

Como comentó @canary255, usar [Firebase](https://firebase.google.com/?hl=es) como backend, sería una solución low-code que seguramente nos permitiría ir muy rápido, a costa del vendor lock-in.

### Infraestructura

- Firebase.

**Comment by Glyan** [comment]
Yo votaría por la opción A, porque creo que es con la que más va a aprender todo el mundo y al final en un proyecto de este estilo hay que aprovechar 👀

Pero si se nos va de presupuesto o no quieren darse cabezazos, mínimo algo como la B. 

Yo soy más de back que de front pero probablemente terminemos tocando todos un poco de todo. Me llama la atención salirnos un poco de React, Vue o Angular con Svelte pero como vean 🙌🏻

Para el back, prefiero algo como NestJS porque es bastante clean de usar y no es dificil de aprender. Les dejo un [link](https://youtu.be/S0R82Osg-Mk) a un canal que hace buenos cursos y eso 👌🏻

**Comment by CaballeroD** [comment]
Yo voto por la opción A, me interesa aprender sobretodo kubernetes, así que optaría por eso. Además de que tenemos 0 prisa con el proyecto en principio, a parte que molaría poder ir acoplando nuevas funcionalidad (atípicas) con el tiempo.

En cuanto a las tecnologías yo aprendo la que sea jajajajaja

**Comment by kevinrobayna** [comment]
Decidimos Vue + Nest.js!!
